import { ProductDataProps } from "./types/product";

export const APP_NAME = "CRACKDO";
export const GITHUB_REPO = "https://github.com/a0v0/aucto";
export const SITE_URL = "https://crackdo.com/";

export const ProductData: ProductDataProps[] = [
  {
    images: [
      "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1508614589041-895b88991e3e?q=80&w=800&auto=format&fit=crop",
    ],
    slug: "1",
    productName: "Advanced Quadcopter Drone 4K",
    category: "Electronics",
    basePrice: 799.99,
    endsInHours: 24,
    description:
      "Explore the skies with our advanced quadcopter drone. Features 4K HDR camera, 3-axis gimbal, 30-min flight time, and obstacle avoidance system.",
    ratings: 0,
    activeBids: 0,
    watchers: 3,
    totalBids: 0,
    reviews: 0,
    bidIncrementBy: 25,
    details: [
      { key: "Brand", value: "DroneTech" },
      { key: "Model", value: "SkyMaster X-500" },
      { key: "Camera", value: "4K Ultra HD 60fps" },
      { key: "Flight Time", value: "30 minutes" },
      { key: "Max Range", value: "2.5 km" },
      { key: "Escrow Status", value: "Verified & Protected" },
    ],
  },
  {
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?q=80&w=800&auto=format&fit=crop",
    ],
    slug: "2",
    productName: "High-Performance Creator Laptop",
    category: "Electronics",
    basePrice: 1299.99,
    endsInHours: 48,
    description:
      "Powerful performance with 32GB Unified Memory, Liquid Retina display, and 1TB SSD storage. Ideal for heavy workloads and creative editing.",
    ratings: 0,
    activeBids: 0,
    watchers: 2,
    totalBids: 0,
    reviews: 0,
    bidIncrementBy: 50,
    details: [
      { key: "Brand", value: "TechMasters" },
      { key: "Processor", value: "12-Core CPU" },
      { key: "RAM", value: "32 GB" },
      { key: "Storage", value: "1 TB SSD" },
      { key: "Display", value: "16.2 inch XDR 120Hz" },
    ],
  },
  {
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=800&auto=format&fit=crop",
    ],
    slug: "3",
    productName: "Wireless Noise-Canceling Headphones",
    category: "Electronics",
    basePrice: 249.99,
    endsInHours: 18,
    description:
      "Active noise cancellation with spatial audio, custom EQ, 40-hour battery life, and ultra-soft memory foam earcups for all-day comfort.",
    ratings: 0,
    activeBids: 0,
    watchers: 4,
    totalBids: 0,
    reviews: 0,
    bidIncrementBy: 15,
    details: [
      { key: "Brand", value: "SoundBliss" },
      { key: "Model", value: "QuietTunes 900" },
      { key: "Color", value: "Midnight Black" },
      { key: "Battery Life", value: "40 hours" },
      { key: "Noise Cancellation", value: "Adaptive ANC" },
    ],
  },
  {
    images: [
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?q=80&w=800&auto=format&fit=crop",
    ],
    slug: "4",
    productName: "Flagship AI Smartphone Pro",
    category: "Electronics",
    basePrice: 899.99,
    endsInHours: 12,
    description:
      "Next-generation smartphone with 200MP AI camera, Titanium chassis, 120Hz LTPO AMOLED display, and intelligent battery optimization.",
    ratings: 0,
    activeBids: 0,
    watchers: 5,
    totalBids: 0,
    reviews: 0,
    bidIncrementBy: 30,
    details: [
      { key: "Brand", value: "TechWonders" },
      { key: "Model", value: "AI Vision X7 Ultra" },
      { key: "Camera", value: "200 MP + Periscope Zoom" },
      { key: "Storage", value: "512 GB" },
      { key: "Display", value: "6.8 inch 120Hz LTPO" },
    ],
  },
  {
    images: [
      "https://images.unsplash.com/photo-1603302576837-37561b2e2302?q=80&w=800&auto=format&fit=crop",
    ],
    slug: "5",
    productName: "Pro Gaming Laptop RTX 4090",
    category: "Gaming",
    basePrice: 2199.99,
    endsInHours: 36,
    description:
      "Esports gaming performance with Intel Core i9, NVIDIA GeForce RTX 4090, 240Hz QHD+ display, and liquid metal cooling.",
    ratings: 0,
    activeBids: 0,
    watchers: 6,
    totalBids: 0,
    reviews: 0,
    bidIncrementBy: 50,
    details: [
      { key: "Brand", value: "GamerXtreme" },
      { key: "GPU", value: "NVIDIA RTX 4090 16GB" },
      { key: "RAM", value: "64 GB DDR5" },
      { key: "Display", value: "240Hz 3ms QHD+" },
    ],
  },
  {
    images: [
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=800&auto=format&fit=crop",
    ],
    slug: "8",
    productName: "Luxury Chronograph Wristwatch",
    category: "Luxury",
    basePrice: 3499.99,
    endsInHours: 72,
    description:
      "Swiss automatic movement chronograph crafted in 18k Rose Gold casing with sapphire crystal back and alligator leather strap.",
    ratings: 0,
    activeBids: 0,
    watchers: 8,
    totalBids: 0,
    reviews: 0,
    bidIncrementBy: 100,
    details: [
      { key: "Brand", value: "TimeLux Geneva" },
      { key: "Movement", value: "Swiss Automatic Calibre" },
      { key: "Case Material", value: "18k Rose Gold" },
      { key: "Water Resistance", value: "100 meters" },
    ],
  },
  {
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=800&auto=format&fit=crop",
    ],
    slug: "6",
    productName: "Smartwatch with Health Monitoring",
    category: "Electronics",
    basePrice: 199.99,
    endsInHours: 24,
    description:
      "Advanced wellness monitoring watch featuring continuous heart rate, ECG recording, GPS tracking, and titanium bezel.",
    ratings: 0,
    activeBids: 0,
    watchers: 2,
    totalBids: 0,
    reviews: 0,
    bidIncrementBy: 15,
    details: [
      { key: "Brand", value: "HealthTech" },
      { key: "Sensors", value: "ECG, SpO2, Temperature" },
      { key: "Battery Life", value: "7 days" },
    ],
  },
  {
    images: [
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=800&auto=format&fit=crop",
    ],
    slug: "13",
    productName: "Professional Mirrorless Camera Kit",
    category: "Electronics",
    basePrice: 2499.99,
    endsInHours: 48,
    description:
      "Full-frame 45MP sensor, 8K video recording, 20fps continuous shooting, and dual card slots with 24-70mm f/2.8 lens included.",
    ratings: 0,
    activeBids: 0,
    watchers: 5,
    totalBids: 0,
    reviews: 0,
    bidIncrementBy: 50,
    details: [
      { key: "Brand", value: "PhotoMaster" },
      { key: "Sensor", value: "45MP Full-Frame CMOS" },
      { key: "Video", value: "8K 30p / 4K 120p" },
    ],
  },
  {
    images: [
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=800&auto=format&fit=crop",
    ],
    slug: "20",
    productName: "Mechanical RGB Gaming Keyboard",
    category: "Gaming",
    basePrice: 149.99,
    endsInHours: 16,
    description:
      "Gasket-mounted hot-swappable mechanical keyboard with lubricated linear switches, PBT keycaps, and per-key RGB backlighting.",
    ratings: 0,
    activeBids: 0,
    watchers: 3,
    totalBids: 0,
    reviews: 0,
    bidIncrementBy: 10,
    details: [
      { key: "Brand", value: "GamerZone" },
      { key: "Switches", value: "Custom Linear Swapped" },
      { key: "Connection", value: "Tri-mode (BT/2.4G/USB-C)" },
    ],
  },
  {
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=800&auto=format&fit=crop",
    ],
    slug: "9",
    productName: "Weatherproof Outdoor Expedition Pack",
    category: "Outdoor",
    basePrice: 129.99,
    endsInHours: 30,
    description:
      "Heavy-duty water-resistant Cordura nylon backpack engineered for mountain trekking with ergonomics support.",
    ratings: 0,
    activeBids: 0,
    watchers: 1,
    totalBids: 0,
    reviews: 0,
    bidIncrementBy: 10,
    details: [
      { key: "Brand", value: "AdventureGear" },
      { key: "Capacity", value: "50 Liters" },
      { key: "Material", value: "1000D Cordura Nylon" },
    ],
  },
  {
    images: [
      "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?q=80&w=800&auto=format&fit=crop",
    ],
    slug: "17",
    productName: "Handmade Acoustic Guitar",
    category: "Luxury",
    basePrice: 899.99,
    endsInHours: 60,
    description:
      "Master-crafted acoustic guitar made from aged Solid Sitka Spruce top and East Indian Rosewood back and sides. Includes hardshell case.",
    ratings: 0,
    activeBids: 0,
    watchers: 4,
    totalBids: 0,
    reviews: 0,
    bidIncrementBy: 25,
    details: [
      { key: "Brand", value: "MelodyCraft Heritage" },
      { key: "Top Wood", value: "Solid Sitka Spruce" },
      { key: "Finish", value: "Nitrocellulose Lacquer" },
    ],
  },
  {
    images: [
      "https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?q=80&w=800&auto=format&fit=crop",
    ],
    slug: "27",
    productName: "Commercial Espresso Machine",
    category: "Electronics",
    basePrice: 649.99,
    endsInHours: 20,
    description:
      "Dual boiler stainless steel espresso machine with PID temperature control, commercial steam wand, and rotary pump.",
    ratings: 0,
    activeBids: 0,
    watchers: 3,
    totalBids: 0,
    reviews: 0,
    bidIncrementBy: 25,
    details: [
      { key: "Brand", value: "CafeMaster Milano" },
      { key: "Boiler Type", value: "Dual Stainless Steel" },
      { key: "Pressure", value: "15 Bar Italian Pump" },
    ],
  },
];
